# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_remove_query_query_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='url',
            field=models.CharField(default='google.com', max_length=100),
            preserve_default=False,
        ),
    ]
