# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_query_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='text',
            field=models.CharField(default=' ', max_length=5000000),
            preserve_default=False,
        ),
    ]
